# -*- coding: utf-8 -*-
"""PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leksIQkROQEl3zr6Y4UBsFEwuoVpYGeR
"""

!pip install ultralytics
!pip install opencv-python
!pip install ultralytics opencv-python pandas xlsxwriter numpy
!pip install xlsxwriter
from ultralytics import YOLO
import cv2
import pandas as pd
import os
import numpy as np
import xlsxwriter
import matplotlib.pyplot as plt

def calculate_iou(boxA, boxB):
    """Calculates Intersection Over Union (IoU) of two bounding boxes."""
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    interArea = max(0, xB - xA) * max(0, yB - yA)
    boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
    boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])
    iou = interArea / float(boxAArea + boxBArea - interArea)
    return iou

VIDEO_FILE_PATH = '/content/drive/MyDrive/dsml project/Adobe Express 2025-11-12 13.16.05.mp4'
OUTPUT_DIR = 'detections_project_excel_output'
MODEL_PATH = 'runs/detect/river_plastic_detector/weights/best.pt'
CONFIDENCE_THRESHOLD = 0.5

IGNORED_CLASSES = ['surfboard', 'bird', 'person', 'boat', 'car']

IOU_THRESHOLD = 0.6
FRAMES_TILL_RELOG = 30

print("--- DSML River Plastic Detection Pipeline with Class Filtering ---")

SNIPS_DIR = os.path.join(OUTPUT_DIR, 'snips')
if not os.path.exists(SNIPS_DIR):
    os.makedirs(SNIPS_DIR)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

detection_data = []
detection_id = 0
tracked_objects = {}
tracking_id_counter = 0

try:
    model = YOLO(MODEL_PATH)
    print("Loaded custom trained model.")
except FileNotFoundError:
    model = YOLO('yolov8n.pt')

cap = cv2.VideoCapture(VIDEO_FILE_PATH)
if not cap.isOpened():
    raise IOError(f"❌ Cannot open video file: {VIDEO_FILE_PATH}")

fps = cap.get(cv2.CAP_PROP_FPS)
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
output_video_path = os.path.join(OUTPUT_DIR, 'detected_river_plastic_video.mp4')

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video_path, fourcc, fps, (frame_width, frame_height))

print("\nStarting frame-by-frame video analysis...")
frame_count = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    current_time_ms = cap.get(cv2.CAP_PROP_POS_MSEC)
    current_second = round(current_time_ms / 1000, 2)

    results = model(frame, conf=CONFIDENCE_THRESHOLD, verbose=False)
    r = results[0]

    if r.boxes:
        for box in r.boxes:
            box_coords = [int(x) for x in box.xyxy[0].tolist()]
            confidence = round(box.conf[0].item(), 4)
            class_id = int(box.cls[0].item())
            class_name = model.names[class_id]

            if class_name in IGNORED_CLASSES:
                continue

            x1, y1, x2, y2 = box_coords

            matched_id = None

            for obj_id, obj_data in tracked_objects.items():
                iou = calculate_iou(box_coords, obj_data['bbox'])

                if iou > IOU_THRESHOLD:
                    matched_id = obj_id
                    tracked_objects[obj_id]['bbox'] = box_coords

                    if (frame_count - obj_data['last_frame']) >= FRAMES_TILL_RELOG:
                        cropped_snip = frame[max(0, y1):min(frame_height, y2),
                                             max(0, x1):min(frame_width, x2)]

                        snip_filename = f"snip_{detection_id:05d}_{class_name}_TID{obj_id}.jpg"
                        snip_path_full = os.path.join(SNIPS_DIR, snip_filename)
                        cv2.imwrite(snip_path_full, cropped_snip)

                        detection_data.append({
                            'Detection_ID': detection_id,
                            'Tracking_ID': obj_id,
                            'Video_Second': current_second,
                            'Class_Name': class_name,
                            'Confidence': confidence,
                            'Snip_File_Path': snip_path_full,
                        })

                        tracked_objects[obj_id]['last_frame'] = frame_count
                        detection_id += 1
                    break

            if matched_id is None:
                new_id = tracking_id_counter
                tracking_id_counter += 1

                tracked_objects[new_id] = {
                    'last_frame': frame_count,
                    'bbox': box_coords
                }

                cropped_snip = frame[max(0, y1):min(frame_height, y2),
                                     max(0, x1):min(frame_width, x2)]

                snip_filename = f"snip_{detection_id:05d}_{class_name}_TID{new_id}.jpg"
                snip_path_full = os.path.join(SNIPS_DIR, snip_filename)
                cv2.imwrite(snip_path_full, cropped_snip)

                detection_data.append({
                    'Detection_ID': detection_id,
                    'Tracking_ID': new_id,
                    'Video_Second': current_second,
                    'Class_Name': class_name,
                    'Confidence': confidence,
                    'Snip_File_Path': snip_path_full,
                })

                detection_id += 1

    out.write(r.plot())

cap.release()
out.release()
cv2.destroyAllWindows()


EXCEL_FILE_PATH = os.path.join(OUTPUT_DIR, 'plastic_waste_report_with_images.xlsx')
workbook = xlsxwriter.Workbook(EXCEL_FILE_PATH)
worksheet = workbook.add_worksheet()

headers = ['Detection ID', 'Tracking ID', 'Video Second', 'Class Name', 'Confidence', 'Image Snip']
col_widths = [12, 12, 15, 15, 12, 25]

for col_num, header in enumerate(headers):
    worksheet.write(0, col_num, header)
    worksheet.set_column(col_num, col_num, col_widths[col_num])

IMAGE_HEIGHT_PIXELS = 100
ROW_HEIGHT_EXCEL = 100

row_num = 1
for data_row in detection_data:
    worksheet.write(row_num, 0, data_row['Detection_ID'])
    worksheet.write(row_num, 1, data_row['Tracking_ID'])
    worksheet.write(row_num, 2, data_row['Video_Second'])
    worksheet.write(row_num, 3, data_row['Class_Name'])
    worksheet.write(row_num, 4, data_row['Confidence'])

    worksheet.set_row(row_num, ROW_HEIGHT_EXCEL)

    worksheet.insert_image(row_num, 5, data_row['Snip_File_Path'],
                          {'x_scale': 0.75, 'y_scale': 0.75})

    row_num += 1

workbook.close()


print(f"\n🎉 Pipeline complete.")
print(f"Total Unique Plastic Detections Logged: {detection_id}")
print(f"Excel Report (filtered and embedded) saved to: {EXCEL_FILE_PATH}")
print(f"Output Video saved to: {output_video_path}")

